// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationApp.Persistence;

#nullable disable

namespace RegistrationApp.Persistence.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20260523213947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationApp.Application.Common.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernorateId = 1,
                            IsActive = true,
                            NameAr = "مصر الجديدة",
                            NameEn = "Heliopolis"
                        },
                        new
                        {
                            Id = 2,
                            GovernorateId = 1,
                            IsActive = true,
                            NameAr = "مدينة نصر",
                            NameEn = "Nasr City"
                        },
                        new
                        {
                            Id = 3,
                            GovernorateId = 1,
                            IsActive = true,
                            NameAr = "التجمع الخامس",
                            NameEn = "Fifth Settlement"
                        },
                        new
                        {
                            Id = 4,
                            GovernorateId = 1,
                            IsActive = true,
                            NameAr = "المعادي",
                            NameEn = "Maadi"
                        },
                        new
                        {
                            Id = 5,
                            GovernorateId = 2,
                            IsActive = true,
                            NameAr = "سموحة",
                            NameEn = "Smouha"
                        },
                        new
                        {
                            Id = 6,
                            GovernorateId = 2,
                            IsActive = true,
                            NameAr = "المنتزة",
                            NameEn = "Montaza"
                        },
                        new
                        {
                            Id = 7,
                            GovernorateId = 2,
                            IsActive = true,
                            NameAr = "المعمورة",
                            NameEn = "Maamoura"
                        },
                        new
                        {
                            Id = 8,
                            GovernorateId = 3,
                            IsActive = true,
                            NameAr = "الدقي",
                            NameEn = "Dokki"
                        },
                        new
                        {
                            Id = 9,
                            GovernorateId = 3,
                            IsActive = true,
                            NameAr = "المهندسين",
                            NameEn = "Mohandessin"
                        },
                        new
                        {
                            Id = 10,
                            GovernorateId = 3,
                            IsActive = true,
                            NameAr = "6 أكتوبر",
                            NameEn = "6th of October"
                        },
                        new
                        {
                            Id = 11,
                            GovernorateId = 4,
                            IsActive = true,
                            NameAr = "بنها",
                            NameEn = "Banha"
                        },
                        new
                        {
                            Id = 12,
                            GovernorateId = 4,
                            IsActive = true,
                            NameAr = "شبرا الخيمة",
                            NameEn = "Shubra El-Kheima"
                        },
                        new
                        {
                            Id = 13,
                            GovernorateId = 5,
                            IsActive = true,
                            NameAr = "المنصورة",
                            NameEn = "Mansoura"
                        },
                        new
                        {
                            Id = 14,
                            GovernorateId = 5,
                            IsActive = true,
                            NameAr = "ميت غمر",
                            NameEn = "Mit Ghamr"
                        });
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Governorates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            NameAr = "القاهرة",
                            NameEn = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            NameAr = "الإسكندرية",
                            NameEn = "Alexandria"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            NameAr = "الجيزة",
                            NameEn = "Giza"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            NameAr = "القليوبية",
                            NameEn = "Qalyubia"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            NameAr = "الدقهلية",
                            NameEn = "Dakahlia"
                        });
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.Address", b =>
                {
                    b.HasOne("RegistrationApp.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistrationApp.Domain.Entities.Governorate", null)
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistrationApp.Domain.Entities.Registration", null)
                        .WithMany("Addresses")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.City", b =>
                {
                    b.HasOne("RegistrationApp.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.Governorate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("RegistrationApp.Domain.Entities.Registration", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
